/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractFactsJson(source: string, language: string): string

export declare function extractPathJson(path: string, source: string): string | null

export declare function supportedLanguages(): Array<string>

export declare function tokenizeJson(source: string, language: string, lite?: boolean | undefined | null): string
